apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: lvms-
namespace: openshift-lvm-storage

resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
- name: controller
  newName: quay.io/lvms_dev/lvms-operator
  newTag: latest
