apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-lvm-storage

resources:
- monitor.yaml
- prometheus_rules.yaml
- metrics_service.yaml
- vgmanager_metrics_service.yaml

replacements:
- source:
    fieldPath: metadata.namespace
    kind: ServiceMonitor
  targets:
  - fieldPaths:
    - spec.endpoints.0.tlsConfig.serverName
    - spec.endpoints.1.tlsConfig.serverName
    options:
      delimiter: .
      index: 1
    select:
      kind: ServiceMonitor
      name: lvms-operator-metrics-monitor
