contact_links:
- name: File a bug report
  url: https://issues.redhat.com/secure/CreateIssueDetails!init.jspa?pid=12332330&issuetype=1&components=12372694&priority=10300&customfield_12316142=26752
  about: Please use the Red Hat Issue Tracker to report bugs.
- name: LVM Storage in OpenShift Container Platform
  url: https://docs.openshift.com/container-platform/latest/storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.html
  about: Refer to the OpenShift Container Platform documentation for information about LVM Storage in OpenShift Container Platform.
