#!/bin/bash
bundle_path="registry.redhat.io/lvms4/lvms-operator-bundle"
pre_release_bundle_path="registry.stage.redhat.io/lvms4/lvms-operator-bundle"
lvms_all_tags="$(skopeo list-tags docker://${pre_release_bundle_path})"
lvms_released_tags="$(skopeo list-tags docker://${bundle_path})"
all_versions=($(echo "${lvms_all_tags}" | yq '[.Tags[] | select(test("^v[[:digit:]]+\.[[:digit:]]+$"))] | join(" ")'))
verbose_versions=$(echo "${lvms_all_tags}" | yq '[.Tags[] | select(test("^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$"))]')
released_versions=$(echo "${lvms_released_tags}" | yq '[.Tags[] | select(test("^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$"))] | join(" ")')
base_template_file="templates/template-base.yaml"
template=$(yq '.Stable.Bundles = []' ${base_template_file})

for i in "${!all_versions[@]}"; do
    maxVersion=""
    minVersion="${all_versions[${i}]}"

    if [ "${i}" -lt ${#all_versions[@]} ] && [ "${i}" -gt 0 ]; then
        maxVersion="${all_versions[${i}-1]}"
    else
        maxVersion="${all_versions[${i}]}"
    fi

    echo "Generating catalog template for LVM Operator ${minVersion}"

    catalog_versions=($(echo "${verbose_versions}" | yq "[.[] | select(contains(\"${maxVersion}\") or contains(\"${minVersion}\"))] | join(\" \")"))

    catalog_template="# WARNING THIS FILE IS AUTOGENERATED - DO NOT EDIT\n${template}"
    for ver in ${catalog_versions[@]}; do
        if [[ " $released_versions " =~ " $ver " ]]; then
            catalog_template=$(echo "${catalog_template}" | yq ".Stable.Bundles += {\"Image\": \"${bundle_path}:${ver}\"}")
        else
            catalog_template=$(echo "${catalog_template}" | yq ".Stable.Bundles += {\"Image\": \"${pre_release_bundle_path}:${ver}\"}")
        fi
    done

    echo -e "${catalog_template}" > "templates/lvm-operator-catalog-${minVersion}-template.yaml"
done
