apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: lvms-operator
  namespace: openshift-lvm-storage
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: lvms-operator
  source: lvms-catalogsource
  sourceNamespace: openshift-lvm-storage
